# Generated by Django 4.0.3 on 2022-03-05 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assortment', '0002_remove_drink_image_remove_pizza_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drink',
            name='id',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='id',
        ),
        migrations.AlterField(
            model_name='drink',
            name='slug',
            field=models.SlugField(max_length=64, primary_key=True, serialize=False, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='slug',
            field=models.SlugField(max_length=64, primary_key=True, serialize=False, unique=True, verbose_name='slug'),
        ),
    ]
