# Generated by Django 4.0.3 on 2022-03-18 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_in_queue', models.CharField(blank=True, max_length=64, verbose_name='name in queue')),
                ('place', models.SmallIntegerField(blank=True, null=True, verbose_name='number of place')),
                ('coupon', models.CharField(blank=True, max_length=255, null=True, verbose_name='coupon')),
                ('comment', models.TextField(blank=True, verbose_name='comment')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='cost')),
                ('json_of_items', models.JSONField(verbose_name='items')),
            ],
            options={
                'verbose_name': 'Архивированный заказ',
                'verbose_name_plural': 'Архивированные заказы',
            },
        ),
    ]
