# Generated by Django 4.0.3 on 2022-03-07 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assortment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_in_queue', models.CharField(max_length=64, verbose_name='name in queue')),
                ('is_registered', models.BooleanField(default=True, verbose_name='is registered')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('paid', models.BooleanField(default=False, verbose_name='paid')),
                ('status', models.SmallIntegerField(choices=[(1, 'Заказ принят'), (2, 'Заказ готовится'), (3, 'Заказ готов'), (4, 'Заказ выдан')], verbose_name='status')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order.order', verbose_name='order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='assortment.product')),
            ],
        ),
    ]
